### ISSUE TITLE
[EPIC] Framework Agnostic

### ISSUE THREAD

**Issue by KSLHacks** [wolf-packs/wolf-core#101]
**Description:** 
The ability to run Wolf with any framework. No framework should bias the design choices of Wolf's interface.

**Acceptance Criteria:**
* Wolf's interface shall be easy to use. (The ability to invoked in any context or scope)
* Provide integration for popular NodeJS backend frameworks in Wolf-Packs
  * Express
  * Microsoft Bot Framework
  * Koa
* Consistent documentation and file structure across all repositories

**Comment by kevinleung23** [comment]
Express and Koa were removed from AC and focus spent on DX on BF integration (examples, docs)
