### ISSUE TITLE
Add ImmutableJS?

### ISSUE THREAD

**Issue by howlowck** [wolf-packs/wolf-core#18]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
We are mutating the pendingWolfState sometimes.  To ensure we are not mutating states, we should use ImmutableJS for our pendingWolfState

**Describe alternatives you've considered**
Alternative is keep what we have, but try really hard to make sure we are not mutating the state.

**Additional context**
NA

**Comment by kevinleung23** [comment]
Do not think the value add would outweigh the cost to change Wolf's state.

![image](https://media.giphy.com/media/3o6ZtgFmhW9BERawYU/giphy.gif)
