### ISSUE TITLE
Make Certain Properties of Slot Optional

### ISSUE THREAD

**Issue by howlowck** [wolf-packs/wolf-core#95]
**Is your feature request related to a problem? Please describe.**
Right now there is a lot of boilerplate code for slots in the ability definition.

**Describe the solution you'd like**
Remove all property except `name` and `prompt` as required in the Slot type definition.

**Describe alternatives you've considered**
Writing a bunch of boilerplate code.

**Additional context**
there should already be sufficient validity checks in the actual source code for only the type definition to be updated.

**Comment by KSLHacks** [comment]
@howlowck does this accurately reflect the changes requested?

```js
// required with user defined values
name: 'firstName',
query: () => 'what is your first name?',

// below are optional properties with default values
retry: () => '', // empty string
validate: (value) => {
      return { isValid: true, reason: null }; // always pass, no reason specified
},
onFill: (value, convoState, { fulfillSlot, setSlotDone, setSlotEnabled, setSlotValue }, { accept, deny, requireConfirmation }) => {
      return; // return with no additional logic
},
```

**Comment by howlowck** [comment]
Yes!
I suppose we can even default the `query` property by setting it to just `_.lowerCase(this.name)` (which is "first name" in the example.

**Comment by kevinleung23** [comment]
Core functionality is complete and tested. @howlowck is looking into making the tests dynamic before a PR.

**Comment by kevinleung23** [comment]
Currently in `alpha.x` release.
