### ISSUE TITLE
Remove Botbuilder dependency

### ISSUE THREAD

**Issue by KSLHacks** [wolf-packs/wolf-core#96]
**Description:**
Wolf should no longer utilize the MSFT Botbuilder middleware pipeline to initialize and run the stages per conversation turn. In an effort to make Wolf conversation framework agnostic, it would be nice for Wolf to be a simple function call that is run on every bot endpoint call.

This call would handle all initialization steps as well as run all Wolf stages. The parameter of this function call would be the state where Wolf can store the Wolf State as well as any user data.

Currently there is a peer dependency on Botbuilder "out of the box". It is not clear how to use Wolf with any other conversational framework.

**Acceptance Criteria:**
* `botbuilder` is not a dependency within project (absent from `package.json`)
* All referenced of `botbuilder` is removed from the `src`

**Comment by kevinleung23** [comment]
scrub `project.json` for all framework references such as MSFT tech such as..

```
"keywords": [
    "botbuilder",
    "Microsoft Bot Framework"
  ]
```
